### ISSUE TITLE
Unhandled NullReferenceException due to missing resource

### ISSUE THREAD

**Issue by factormystic** [liveservices/LiveSDK-for-Windows#13]
The defect is that while `ApiOperation` can create a `LiveConnectException` exception for `NoResponseData` errors...

https://github.com/liveservices/LiveSDK-for-Windows/blob/master/src/Common/Source/Internal/Operations/ApiOperation.cs#L128

...there is no corresponding `NoResponseData` resource here (and probably the other resource files/platform targets)...

https://github.com/liveservices/LiveSDK-for-Windows/blob/master/src/WinStore/Source/Resources.resx

...so, the following line blows up as a null ref exception because you're trying to grab a resource that doesn't exist...

https://github.com/liveservices/LiveSDK-for-Windows/blob/master/src/WinStore/Source/Internal/ResourceHelper.cs#L46

...thus, NoResourceData errors result in NullReferenceExceptions, which is incorrect.

**Comment by peternied** [comment]
Wow, that is pretty terrible!
