### ISSUE TITLE
OneDrive SDK does not support notifications (toast+tile) for background transfers

### ISSUE THREAD

**Issue by th3br41n** [liveservices/LiveSDK-for-Windows#21]
I would suggest to trigger an event just after the creation of a Background task (download and/or upload). This could allow developers to set advanced options for the just-created background task (e.g., FailureTileNotification, SuccessTileNotification).

For example in the file CreateBackgroundDownloadOperation.cs, the method OnExecute() could be:
protected async override void OnExecute()
{
  [...]
  var downloader = new BackgroundDownloader();
  if (this.LiveClient.OnCreateBackgroundDownloader!=null) {
    this.LiveClient.OnCreateBackgroundDownloader(this.LiveClient, this.Url, downloader);
  }
  [...]
}

**Comment by peternied** [comment]
Thanks for the suggestion we are not looking to add enhancements to the Windows LiveSDK at this time.  However; I will gladly review pull requests.
