### ISSUE TITLE
Possibly null ref exception after remote tos update

### ISSUE THREAD

**Issue by factormystic** [liveservices/LiveSDK-for-Windows#23]
I was working on my app tonight, using a VM that had been open for several days, using an account that had previously been working fine to connect to OneDrive.

Tonight, attempting to authenticate with that account threw a null reference exception. I thought maybe live services was down, but everything was green. I logged in with another account and noticed that there was a mandatory TOS update acceptance screen.

I killed the VM and logged in to the same (problem) account on a fresh VM... and got an updated TOS screen during authentication. Then everything was fine.

Therefore, I'm guessing there's an edge case around this, where maybe an account already has an auth token and it's now invalid due to updated TOS, or another scenario where the new TOS hasn't yet been accepted but the SDK can't handle the rejected auth.

**Comment by peternied** [comment]
Do you have a call stack on this error?  Happy to dig in if you can give me somewhere to poke at.

**Comment by factormystic** [comment]
I have no other info besides what I wrote and I don't know of any way to simulate this situation since it was tied to a remote server event.

**Comment by peternied** [comment]
I'll keep my eyes out for the error on SO and over here, if this crops up again I can address it.
