### ISSUE TITLE
Why LiveAuthRequestUtility.RefreshTokenAsync() is not public?

### ISSUE THREAD

**Issue by horacioj** [liveservices/LiveSDK-for-Windows#24]
Hi,
Why LiveAuthRequestUtility.RefreshTokenAsync() is not public?
Here http://msdn.microsoft.com/en-us/library/dn631817.aspx (Windows desktop apps documentation) says "Tip  If the wl.offline_access scope is specified, a refresh token is also provided.
Your app can read the authorization code from the returned URL, and use it to retrieve an access token by making a call that passes a URL similar to this one."
The SDK is doing it, in LiveAuthRequestUtility.RefreshTokenAsync()  but this class is internal.
Why it is not public? It will allow custom code to simply call LiveAuthRequestUtility.RefreshTokenAsync() to get a fresh valid session object.
Thanks

**Comment by peternied** [comment]
I don't see any reason to keep it internal if you want to use it.  Submit a pull request after you get it doing what you need any I'll happily take a look
