### ISSUE TITLE
Secret keys list was hard-coded when decoding authentication token

### ISSUE THREAD

**Issue by euyuil** [liveservices/LiveSDK-for-Windows#3]
The issue is in currently the latest commit, version 5.4: https://github.com/liveservices/LiveSDK-for-Windows/commit/90604b50446bb89fe35c089030cf62c94e32772d

When Windows Live returns me the authentication code, running

``` C#
liveLoginResult = await liveAuthClient.ExchangeAuthCodeAsync(HttpContext);
```

throws exception

> Could not find key with id 1

After that I looked into the code, and I found that in function `DecodeAuthenticationToken`, secret keys list was hard-coded ([see here](https://github.com/liveservices/LiveSDK-for-Windows/blob/90604b50446bb89fe35c089030cf62c94e32772d/src/Web/Source/Internal/Utilities/LiveAuthWebUtility.cs#L58)). The key of the only item was hard-coded to `0`.

But when validating the token ([see here](https://github.com/liveservices/LiveSDK-for-Windows/blob/90604b50446bb89fe35c089030cf62c94e32772d/src/Web/Source/Internal/Utilities/JsonWebToken.cs#L100)), there is a `Envelope.KeyId`, which indicates the version number of the client secret key. This number could be increased as you click `Create a new client secret` in API Settings of Live Connect Developer Center.

As the hard-coded `0` and `Envelope.KeyId` mismatches, the exception was thrown. But I don't think the token is invalid.

**Comment by digitalgym** [comment]
Issue still exists in version 5.6
