### ISSUE TITLE
Nuget Package is out of date!

### ISSUE THREAD

**Issue by peternied** [liveservices/LiveSDK-for-Windows#36]
Looks like the nuget package is very much out of date with this repository http://www.nuget.org/packages/LiveSDK

**Comment by rgregg** [comment]
I know how to publish a new one, if someone builds it ☺.

**Comment by peternied** [comment]
LiveSDK 5.6.1 was uploaded to https://www.nuget.org/packages/LiveSDK/ today. this is resolved!
