### ISSUE TITLE
Nuget Package is still using custom IProgress<T> in .NET 4.5

### ISSUE THREAD

**Issue by paya-cz** [liveservices/LiveSDK-for-Windows#41]
I use Nuget Package in my .NET 4.5 app, and the `Microsoft.Live.dll` seems to still reference to assembly `System.Runtime, Version=2.5.19.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a` because of the `IProgress<T>` that is absent in .NET 4.0. Would it be possible to update the Nuget Package to include special version for .NET 4.5 that would get rid of the no-longer-required dependencies, so I can use `IProgress<T>` from the .NET 4.5 mscorlib?

**Comment by peternied** [comment]
If you are looking for a different build of the package, I would recommend using this source code to produce something in line with your requirements.  The build/signing/packaging process that is used for this project is not something that we have the bandwidth to update at this time.
