### ISSUE TITLE
Subscribe calendar in windows phone

### ISSUE THREAD

**Issue by sohanvanani** [liveservices/LiveSDK-for-Windows#42]
i have looked at here https://msdn.microsoft.com/en-us/library/hh826523.aspx  i want to subscribe my outlook calendar in my app by user i have added wl.calendars_update scope.  i dont know where to put my subscribe url of calendar.    i have replaced my url of calendar with this webcal://ical.mac.com/fredduck/Anime47Game32Birthdays.ics url as showed in code  
Here is code:
private async void btnSubscribe_Click(object sender, RoutedEventArgs e)
{
    try
    {
        LiveConnectClient liveClient = new LiveConnectClient(this.session);
        var calendar = new Dictionary<string, object>();
        calendar.Add("name", "Anime/Game Character Birthdays");
        calendar.Add("subscription_url", "webcal://ical.mac.com/fredduck/Anime47Game32Birthdays.ics");
        LiveOperationResult operationResult = await liveClient.PostAsync("me/calendars", calendar);
        this.infoTextBlock.Text = "Calendar subscribed.";
    }
    catch (LiveConnectException exception)
    {
        this.infoTextBlock.Text = "Error subscribing to calendar: " + exception.Message;
    }
}

it subscribe only name of calendar. it doesnt subscribe the all agenda and events of my calendar please help me. sorry for my bad english. simply i just want to subscribe my calendar with my app users.

**Comment by VenkatAyyadevara-MSFT** [comment]
FYI - We are on a path to offer one REST API to access mail, calendar and contact info for both Outlook.com and Office 365 and that endpoint would be different from Live Connect APIs and replace them.  Currently, the REST APIs we are working on, are already offered for Office 365 users and you can check out the API reference at https://msdn.microsoft.com/office/office365/APi/api-catalog. Supporting outlook.com users is currently being worked on but I don't have a firm timeline to share yet.  If you are not dealing with an urgent timeline, I would recommend for you to wait for these APIs.  Thanks.

**Comment by sohanvanani** [comment]
See my question on this https://social.msdn.microsoft.com/Forums/onedrive/en-US/cab14949-b23a-4b71-8591-78d4696c9900/subscribe-calendar-using-liveconnect-client?forum=messengerconnect#cab14949-b23a-4b71-8591-78d4696c9900

There is some apps available on the store which sync calendar like this. http://www.windowsphone.com/en-us/store/app/wc-2015-calendar-sync/2d8d0f6a-5344-4337-86c8-dfc07da5a845 
please help me how to do this.

**Comment by peternied** [comment]
@sohanvanani Looking quickly at the REST reference https://msdn.microsoft.com/en-us/library/hh243648.aspx#calendar, I see that he json element is called 'subscription_location', whereas you have 'subscription_url'.

I would recommend working with that reference to see if you can get your scenario working as you'd expect.

**Comment by sohanvanani** [comment]
Thanks now it works great....
