### ISSUE TITLE
NullReferenceException at Microsoft.Live.ResourceHelper.GetString()

### ISSUE THREAD

**Issue by Tolyandre** [liveservices/LiveSDK-for-Windows#43]
Hi, I've created an empty windows phone 8.1 application and trying to make Live auth.

I getting error:

       "An exception of type 'System.NullReferenceException' occurred in Microsoft.Live.DLL" 

with following stack ('Show Parameter Values' is turned on in Visual Studio call stack):

	Microsoft.Live.DLL!Microsoft.Live.ResourceHelper.GetString(string name = "UrlInvalid")	
 	Microsoft.Live.DLL!Microsoft.Live.LiveAuthClient.LiveAuthClient(string redirectUri = "0000000048087CFD")	

It seems that some internal resource string "UrlInvalid" is missing and exception with another type should be raised. I use latest verson from nuget, that is Live SDK 5.6.1

My code looks like this:

        private void InitializePage()
        {
            try
            {
                this.authClient = new LiveAuthClient("0000000048087CFD"); // <-- Exception here
                 // other code
            }
            catch (LiveAuthException authExp)
            {
                this.tbResponse.Text = authExp.ToString();
            }
        }

**Comment by peternied** [comment]
Looking into patching this up once and for all...
