### ISSUE TITLE
Server is always offline when moving non-existent file

### ISSUE THREAD

**Issue by paya-cz** [liveservices/LiveSDK-for-Windows#45]
This is a little corner case and I am afraid it's not really a problem of this library (but rather server-side bug), but hopefully the issue could get delegated to the proper department.

- Let's say I create 2 folders in the OneDrive root, whose IDs are stored in **folder1** and **folder2** variables.
- I upload new file to **folder1**, and store the file's ID in **file1** variable
- I delete the file and both folders on the OneDrive storage
- I try to move **file1** to **folder2**, despite the fact that neither of them exists

Now, I would expect the library to throw an exception pretty soon (as the request hits the server and response returns) stating that **file1** and **folder2** do not exist, but instead I have to wait for a timeout and then I get the following exception:

![image](https://cloud.githubusercontent.com/assets/10402560/7077571/2a186f76-df12-11e4-8f41-715ee4aba61f.png)

**Comment by peternied** [comment]
Could you use http://www.telerik.com/download/fiddler to capture a trace of what the client did?  I would expect you to get a 404 right away if the file was not around, this is tingling my code smell sense...

**Comment by paya-cz** [comment]
Client request:

> MOVE https://apis.live.net/v5.0/file.xxx.xxx!xxx?suppress_response_codes=true&suppress_redirects=true HTTP/1.1
> Accept: */*
> Authorization: bearer xxxxx
> X-HTTP-Live-Library: Windows/.Net4_1.0Client
> Content-Type: application/json;charset=UTF-8
> Host: apis.live.net
> Content-Length: 68
> Expect: 100-continue
>
> { "destination" : "folder.xxx.xxx!xxx" }

Server response:

> HTTP/1.1 504 Fiddler - Receive Failure
> Date: Thu, 09 Apr 2015 22:34:51 GMT
> Content-Type: text/html; charset=UTF-8
> Connection: close
> Cache-Control: no-cache, must-revalidate
> Timestamp: 00:34:51.439
>
> [Fiddler] ReadResponse() failed: The server did not return a complete response for this request. Server returned 0 bytes.

To get that Fiddler response, I had to wait for 30-60 seconds, at which point I got that LiveConnectException saying that server is offline. No 404 anywhere...

**Comment by paya-cz** [comment]
Btw the same problem appears to be with "Copy" too, as long as both the file and target folder do not exist. If any one of them exists, both "Copy" and "Move" return error response correctly. But I guess that's just because "Copy" and "Move" share the same request handling code at the server.

**Comment by peternied** [comment]
I'm activity investigating this issue

**Comment by peternied** [comment]
I found the underlying issue, requests will stall on a Move or Copy where the destination folder does not exist.  I'll circle back when the issue has been fixed.

**Comment by peternied** [comment]
@paya-cz Could you check and see if this problem persists?

**Comment by paya-cz** [comment]
@peternied The problem still persists and the server response did not change - I still get the same fiddler output, and it takes about 30 seconds for the Move/Copy request to timeout.

**Comment by peternied** [comment]
I've got a fix that should prevent requests from stalling out, I'll let you know when it is available to try out

**Comment by peternied** [comment]
This fix is avaliable, please reopen if you continue to experience problems
