### ISSUE TITLE
Server does not seem to be 100% consistent

### ISSUE THREAD

**Issue by paya-cz** [liveservices/LiveSDK-for-Windows#48]
So over the last few days I was doing a lot of testing and debugging, including uploading over 10 000 files to OneDrive (all pretty much into a single directory). However, at 8 occasions the server replied that the directory does not exist, even though it clearly 100% does exist (since I uploaded thousands of files to that very directory before and after...). To upload all those files, I always had about 100 outstanding requests, but these "folder does not exist" errors were almost always completely isolated instances. Twice, I got 2 of these error in succession.

I have no idea what could be the cause of such issue and it is very hard to reproduce, but it worries me greatly because whenever I get a response that "directory does not exist", I can no longer be 100% sure that it really does not exist... So should I always check 2 or 3 times whether the folder really does not exist, so the probability of error is super low? That would inflate the request count a lot...

**Comment by peternied** [comment]
@paya-cz I'm looking into our error handling to see why you'd get back a misleading error message like this.  It would really help me out if you could send me some information about the account that was being used at the time, could you [email me](pnied@microsoft.com) the account's email address and/or a fiddler trace of a request that failed?

**Comment by paya-cz** [comment]
I just sent you an e-mail. Please let me know if you did not receive any and I will try to resend.

**Comment by peternied** [comment]
I'm looking into this offline.

**Comment by peternied** [comment]
We were having a service issue when you reported these failures, and it exposed a defect in the ItemNotFound reporting logic.  The underlying service issue has been corrected, thanks for reporting this.

**Comment by paya-cz** [comment]
Thanks for fixing this.
