### ISSUE TITLE
WinStore: Crash at Microsoft.Live.ResourceHelper.GetString(String name)

### ISSUE THREAD

**Issue by ymoldavanov** [liveservices/LiveSDK-for-Windows#54]
WinStore: Crash at Microsoft.Live.ResourceHelper.GetString(String name)

My WinStore app's UnhandledException handler received exception from LiveSDK (version 5.6.2.0, see full stack trace below). It happens when no internet exception. I can't use try/cath to catch it since TryRefreshToken is async VOID method and my app crashes.
Similar problem: https://social.msdn.microsoft.com/Forums/en-US/e897a135-52c7-45c3-bab9-2ee94803d876/systemnullreferenceexception-while-calling-c-runtime-component-from-javascript?forum=winappswithcsharp
and here: http://stackoverflow.com/questions/15656966/nullreferenceexception-while-calling-loginasync
and here: https://social.msdn.microsoft.com/Forums/onedrive/en-US/756926c9-6bdb-4336-913e-b3a05bd686d9/liveauthclient-initializeasync-exception?forum=messengerconnect
and more...

Why resources are missing?

UNHANDLED EXCEPTION: Object reference not set to an instance of an object.
at Microsoft.Live.ResourceHelper.GetString(String name)
at Microsoft.Live.Operations.ApiOperation.CreateOperationResultFrom(WebResponse response)
at Microsoft.Live.Operations.ApiOperation.OnWebResponseReceived(WebResponse response)
at Microsoft.Live.Operations.WebOperation.OnGetResponseCompleted(IAsyncResult ar)
at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
at System.Net.ContextAwareResult.CaptureOrComplete(ExecutionContext& cachedContext, Boolean returnContext)
at System.Net.ContextAwareResult.FinishPostingAsyncOp()
at System.Net.HttpWebRequest.BeginGetResponse(AsyncCallback callback, Object state)
at Microsoft.Live.Operations.ApiOperation.OnExecute()
at Microsoft.Live.Operations.Operation.InternalExecute()
at Microsoft.Live.Operations.ApiOperation.OnRefreshTokenOperationCompleted(LiveLoginResult result)
at Microsoft.Live.LiveAuthClient.<TryRefreshToken>d__e.MoveNext()

**Comment by ymoldavanov** [comment]
Easy steps to reproduce resources issue:
1. Create new blank C# project
2. Nuget Packages - > find and install LiveSDK.5.6.2
3. invoke method test()
using Microsoft.Live;

        async void test()
        {
            LiveAuthClient _LiveAuthClient = new LiveAuthClient("http://www.ximad.com");
            await _LiveAuthClient.InitializeAsync();
        }

Expected: Exception "The app is not configured correctly to use Live Connect services. To configure your app, please follow the instructions on http://go.microsoft.com/fwlink/?LinkId=220871." at Microsoft.Live.LiveAuthClient.<ExecuteAuthTaskAsync>d__8.MoveNext()

Actual: Null reference exception "Object reference not set to an instance of an object." 
"   at Microsoft.Live.ResourceHelper.GetString(String name)\r\n
   at Microsoft.Live.TailoredAuthClient.<AuthenticateAsync>d__0.MoveNext()\r\n
...
   at Microsoft.Live.LiveAuthClient.<ExecuteAuthTaskAsync>d__8.MoveNext()\r\n
...
   at App2.App.<test>d__0.MoveNext() "

Note, all works as expected if compile dll from source and copy Microsoft.Live.pri and Microsoft.Live\SDKManifest.xml into App2\packages\LiveSDK.5.6.2\WindowsXAML folder (beside Microsoft.Live.dll from nuget package)

**Comment by ymoldavanov** [comment]
BTW. Same issue if install 5.6 via LiveSDK.msi. When installation is completed folder c:\Program Files (x86)\Microsoft SDKs\Live\v5.6\Windows Store app XAML\References\CommonConfiguration\Neutral\Microsoft.Live.dll" does NOT contain PRI file

**Comment by peternied** [comment]
We fixed this issue, however it looks like the NuGet package was not updated with the newer version of the binaries

**Comment by peternied** [comment]
Ok, figured out what is going wrong, apparently nuget packed does have the correct DLL for some platforms, but for other platforms it does not specifically anything that uses WindowsXAML.  I'm working on repairing the package

**Comment by Gellore** [comment]
Is NuGet package going to be updated with this fix? It's kind of critical one. If not, where can I get Live SDK with this fix?

**Comment by peternied** [comment]
Yes there will be a nuget release 5.6.3 that will have the fix in it, it will take a little time as our signing process doesn't happen over weekends. I'll be sure to reach out when it is available. Until that time can you be unblocked with updated source?

**Comment by Gellore** [comment]
I took your fork's ResourceHelper branch and it seems to be working fine, thanx.

**Comment by peternied** [comment]
@Gellore and @ymoldavanov I've updated the nuget package, please open another bug if there is any trouble there.
