### ISSUE TITLE
Custom avatars cannot be loaded, the default one works fine

### ISSUE THREAD

**Issue by Gellore** [liveservices/LiveSDK-for-Windows#57]
When I run APIExplorer sample app for Windows 8.1, and my account doesn't have a custom picture, it loads just fine. When I change it to some custom image, it doesn't work anymore. App is associated with windows store application.

I've tried it both ways, first one (that's how it's by default):

```c#
            try
            {
                LiveDownloadOperation operation = await this.liveClient.CreateBackgroundDownloadAsync("me/picture");
                LiveDownloadOperationResult result = await operation.StartAsync();
                if (result != null && result.Stream != null)
                {
                    using (IRandomAccessStream ras = await result.GetRandomAccessStreamAsync())
                    {
                        BitmapImage imgSource = new BitmapImage();
                        imgSource.SetSource(ras);
                        this.imgMe.Source = imgSource;
                    }
                }
            }
            catch (LiveConnectException e)
            {
                this.tbResponse.Text = e.ToString();
            }
```

Another one:

```c#
            LiveOperationResult operationResult = await liveClient.GetAsync("me/picture");
            dynamic result = operationResult.Result;
            BitmapImage image = new BitmapImage(new Uri(result.location, UriKind.Absolute));
            this.imgMe.Source = image;
```

The cause might be that when I have no avatar, location (returned by me/picture) is **https://js.live.net/static/img/DefaultUserPicture.png**. But when I change it to something, it changes to some redirect link (it looks like this): **https://cid-xxxxxx.users.storage.live.com/users/xxxxx/myprofile/expressionprofile/profilephoto:UserTileStatic**. This Url actually gives a "Log In" page html code.

**Comment by peternied** [comment]
@Gellore This looks like a bug in that code, as APIExplorer app isn't passing the auth creds to get the image, you need to be authenticated to get a users profile photo.

You can quickly double check this by watching the requests from the APIExplorer with Fiddler and then adding the Authenciation header to that request that 302'ed to the Log In page

**Comment by peternied** [comment]
Deleting this old issue
