### ISSUE TITLE
Bug with the embedded resources

### ISSUE THREAD

**Issue by DecorteHannes** [liveservices/LiveSDK-for-Windows#8]
When for instance there is a network problem (timeout) the code tries to get a resource ("ConnectionError"), but that fails (see below). Seems to have something todo with the Custom Tool NameSpace on de resources.resc file. If I remove the namespace it works.

Exception:

An unhandled exception of type 'System.Resources.MissingManifestResourceException' occurred in System.dll

Additional information: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Microsoft.Live.Resources.resources" was correctly embedded or linked into assembly "Microsoft.Live.Web" at compile time, or that all the satellite assemblies required are loadable and fully signed.

**Comment by peternied** [comment]
Thanks for reporting this, did you see this on an emulator or on a device?

**Comment by peternied** [comment]
Actually I see that this issue is reproducible on the sample applications, working on a fix
