### ISSUE TITLE
You have to register your app with the Windows (Phone) Store

### ISSUE THREAD

**Issue by factormystic** [liveservices/LiveSDK-for-Windows#9]
If you create a new app from scratch and try to use the Live SDK, you're going to get an unhandled exception when you try to authenticate. This is because you have to register your app with the Windows/Windows Phone store. This is easy to do in Visual Studio 2013 by right clicking your Project > Store > Associate app with the store... and following the wizard.

I wasted a couple of hours trying to figure this out, because as far as I can tell it's not actually documented anywhere, and the SDK samples "just work" with no indication that this is a prerequisite.

**Comment by peternied** [comment]
Thanks for the feedback, closing out this issue!
